package com.ft.sdk.garble.bean;

/**
 * description: Type of data uploaded
 */
public enum DataType {

    /**
     * Native App RUM data
     */
    RUM_APP,

    /**
     * Unsampled data cache
     */
    RUM_APP_ERROR_SAMPLED,
    /**
     * RUM data generated by JS in WebView, requires configuration
     * <a href="https://github.com/GuanceCloud/datakit-js"> JS SDK</a>
     */
    RUM_WEBVIEW,

    /**
     * Unsampled data cache
     */
    RUM_WEBVIEW_ERROR_SAMPLED,

    /**
     * SDK Log data
     */
    LOG,
//    /**
//     * SDK Trace data, currently not used
//     */
//    TRACE
    ;

    public final static String ERROR_SAMPLED_SUFFIX = "_error_sampled";

    public String getValue() {
        return toString().toLowerCase();
    }

}
