package com.ft.sdk.garble.bean;

import com.ft.sdk.garble.utils.Constants;

import java.util.HashMap;
import java.util.Map;

/**
 * create: by huangDianHua
 * time: 2020/6/5 15:08:45
 * description: Log object (for internal SDK use)
 */
public class LogBean extends BaseContentBean {
    /**
     * Specify the source of the current log, for example, if the source is Nginx, it can be specified as Nginx.
     * The log source generated by the same application should be the same, so that it is convenient to configure the same extraction rules for the log source in the observability cloud.
     * Log level
     */
    String status = Status.INFO.name;

    /**
     * Extended properties
     */
    HashMap<String, Object> property = new HashMap<>();

    public HashMap<String, Object> getProperty() {
        return property;
    }

    public LogBean(String content, long time) {
        super(content, time);
    }

    /**
     * Get all metric data in the log
     *
     * @return
     */
    public HashMap<String, Object> getAllFields() {
        super.getAllFields();
        if (!property.isEmpty()) {
            for (Map.Entry<String, Object> entry : property.entrySet()) {
                String key = entry.getKey();
                Object value = entry.getValue();
                fields.put(key, value);
            }
        }
        return fields;
    }

    /**
     * Get all tag data in the log
     *
     * @return
     */
    public HashMap<String, Object> getAllTags() {
        super.getAllTags();
        tags.put(Constants.KEY_STATUS, status);
        return tags;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


}
